<?php
/*
 *
 * @category   Community
 * @package    MagentoCenter_Wm
 * @copyright  http://Magentocenter.org
 * @license    Open Software License (OSL 3.0)
 *
 */

/*
 * Webmoney Transfer payment module
 *
 * @author     Magentocenter.org    -   Magento Store Setup, data migration, upgrades and much more!
 *
 */
echo $this->__('Webmoney');

$orderId = $this->getRequest()->getParam('order_id', false);

if($orderId) {
    $url=$this->getMethod()->getOrderPlaceRedirectUrl();
    echo ' | <a href="'.$url.'">'. $this->__('Payment for order #').$orderId.' </a>';
}

?>

